name: Release

on:
  workflow_dispatch: {}
  release:
    types: [published]

env: 
  CI: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  MSBUILDTERMINALLOGGER: off
      
jobs:
  build:
    uses: ./.github/workflows/ci.yml
    if: contains('["Swimburger","dprothero","AJLange"]', github.actor)
    name: Build, test, and pack
    permissions:
      checks: write
    secrets: inherit

  release:
    if: contains('["Swimburger","dprothero","AJLange"]', github.actor)
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
          
      - uses: actions/download-artifact@v4
        name: Download Twilio.AspNet.Common NuGet Package
        with:
          name: Twilio.AspNet.Common NuGet Package
          
      - uses: actions/download-artifact@v4
        name: Download Twilio.AspNet.Core NuGet Package
        with:
          name: Twilio.AspNet.Core NuGet Package
          
      - uses: actions/download-artifact@v4
        name: Download Twilio.AspNet.Mvc NuGet Package
        with:
          name: Twilio.AspNet.Mvc NuGet Package
          
      - name: (Twilio.AspNet.Common) Push to NuGet
        run: |
          dotnet nuget push 'Twilio.AspNet.Common.*.nupkg' \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json
          
      - name: (Twilio.AspNet.Core) Push to NuGet
        run: |
          dotnet nuget push 'Twilio.AspNet.Core.*.nupkg' \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json
      
      - name: (Twilio.AspNet.Mvc) Push to NuGet
        run: |
          dotnet nuget push 'Twilio.AspNet.Mvc.*.nupkg' \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json
